### ISSUE TITLE
username or password incorrect

### ISSUE THREAD

**Issue by dormeir99o** [unRob/CouchSurfing-API#5]
Hi Rob!

First, let me say your API has an amazing functionality!
Q: Where in the code do I put in my username and password?
I'm not strong in Ruby programming, but from what I see in the example file,
 it has something to do with the "initialize" module in /lib/CSApi.rb - 

    def initialize(username, password)
      @username = username
      r = HTTP.post('/sessions', body:{username: username, password: password}.to_json)

      raise CS::AuthError.new("Could not login") if r.code != 200

      @cookies = []
      @cookies=r.headers['Set-Cookie'].split(/;/).first
      #end

Can you please help?

Thanks!

Dor

**Comment by unRob** [comment]
Hey there Dor, were you able to take a look at the [example](https://github.com/unRob/CouchSurfing-API/blob/master/examples/example.rb#L11)? Try following along that code, using your credentials for `CS::Api.new(user, password)`; `user` and `password` are variables containing your credentials.

**Comment by dormeir99o** [comment]
Hey Rob,

That's the first thing I tried, not working..
I confirmed that the same copied user and pass do work for the website.
This is what I put it in the example.rb:
![image](https://cloud.githubusercontent.com/assets/17915074/21177327/556751cc-c1f3-11e6-9693-49f92f67150e.png)
and when running, I get:
Incorrect username or password

**Comment by unRob** [comment]
I'm sorry Dor, I tried it myself and see an error as well due to CS updating their API in a way this unofficial client/wrapper is not able to handle. I haven't touched this code in more than a couple of years, and currently don't want to add more hours of coding to my day. That means that unfortunately I won't be able to help you work through this issue, since it'd involve a potentially substantial rewrite of this project. I will, however, add a notice about this, and thanks for letting me know how broken this project is!

**Comment by dormeir999** [comment]
Hey Rob,
Thanks for trying, I appreciate it..
